/* HVAC PRO - databases/acervo_tecnico.js
   CORRECAO ESTRUTURAL - BUSCA POR CODIGO EXATO

   INSTRUCAO:
   1. Abra databases/acervo_tecnico.js
   2. Apague TUDO
   3. Cole este arquivo inteiro
   4. Commit changes
   5. Abra o app com ?v=6000

   O QUE FOI CORRIGIDO:
   - Codigo exato de etiqueta agora aponta para ficha individual.
   - Gree, Midea, Elgin, Komeco, LG, Samsung, Consul, Electrolux, Philco, TCL, Agratto, Daikin e Hitachi foram separados por codigo/potencia quando havia codigo claro.
   - Cadastro generico de familia continua existindo somente para busca por marca/linha, sem roubar busca de codigo exato.
   - Sem funcoes, sem bloco extra, sem mexer no app.js.
*/

window.acervoTecnico = [

  {
    "marca": "Midea",
    "modelo": "Midea Xtreme Save AI Connect AGVCJ R32 9000 BTU",
    "codigoBusca": ["42AGVCJ09M5", "38AGVCJ09M5", "42AGVCJ09", "38AGVCJ09", "AGVCJ09", "MIDEA 9000 R32", "XTREME SAVE AI CONNECT 9000"],
    "linha": "Xtreme Save AI Connect",
    "tipo": "Split Hi Wall Inverter Frio",
    "capacidade": "9000 BTU/h",
    "tensao": "220V",
    "fluidoRefrigerante": "R32",
    "cargaGas": "320 g ate 5 m",
    "correnteNominal": "Validar etiqueta da unidade externa 38AGVCJ09M5",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "disjuntor": "Validar tabela do manual e instalacao eletrica local",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "tubulacaoAlta": "1/4 pol.",
    "tubulacaoBaixa": "3/8 pol.",
    "comprimentoMaximo": "25 m",
    "desnivelMaximo": "10 m",
    "manualInstalacao": "https://conteudo.midea.com.br/manuais/Ar-Condicionado-Midea-Inverter-Xtreme-Save-AI-Connect.pdf",
    "manualManutencao": "https://conteudo.midea.com.br/manuais/Ar-Condicionado-Midea-Inverter-Xtreme-Save-AI-Connect.pdf",
    "fonte": "Base tecnica HVAC PRO - Midea AGVCJ09",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "tensao": "OFICIAL", "fluidoRefrigerante": "OFICIAL", "cargaGas": "CONFIAVEL_NAO_OFICIAL", "correnteNominal": "INFORMACAO_SUGERIDA", "correnteTrabalho": "INFORMACAO_SUGERIDA", "disjuntor": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA", "tubulacaoAlta": "CONFIAVEL_NAO_OFICIAL", "tubulacaoBaixa": "CONFIAVEL_NAO_OFICIAL", "comprimentoMaximo": "CONFIAVEL_NAO_OFICIAL", "desnivelMaximo": "CONFIAVEL_NAO_OFICIAL" }
  },

  {
    "marca": "Midea",
    "modelo": "Midea Xtreme Save AI Connect AGVCJ R32 12000 BTU",
    "codigoBusca": ["42AGVCJ12M5", "38AGVCJ12M5", "42AGVCJ12", "38AGVCJ12", "AGVCJ12", "MIDEA 12000 R32", "XTREME SAVE AI CONNECT 12000"],
    "linha": "Xtreme Save AI Connect",
    "tipo": "Split Hi Wall Inverter Frio",
    "capacidade": "12000 BTU/h",
    "tensao": "220V",
    "fluidoRefrigerante": "R32",
    "cargaGas": "440 g ate 5 m",
    "correnteNominal": "Validar etiqueta da unidade externa 38AGVCJ12M5",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "disjuntor": "Validar tabela do manual e instalacao eletrica local",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "tubulacaoAlta": "1/4 pol.",
    "tubulacaoBaixa": "3/8 pol.",
    "comprimentoMaximo": "25 m",
    "desnivelMaximo": "10 m",
    "manualInstalacao": "https://conteudo.midea.com.br/manuais/Ar-Condicionado-Midea-Inverter-Xtreme-Save-AI-Connect.pdf",
    "manualManutencao": "https://conteudo.midea.com.br/manuais/Ar-Condicionado-Midea-Inverter-Xtreme-Save-AI-Connect.pdf",
    "fonte": "Base tecnica HVAC PRO - Midea AGVCJ12",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "tensao": "OFICIAL", "fluidoRefrigerante": "OFICIAL", "cargaGas": "CONFIAVEL_NAO_OFICIAL", "correnteNominal": "INFORMACAO_SUGERIDA", "correnteTrabalho": "INFORMACAO_SUGERIDA", "disjuntor": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA", "tubulacaoAlta": "CONFIAVEL_NAO_OFICIAL", "tubulacaoBaixa": "CONFIAVEL_NAO_OFICIAL", "comprimentoMaximo": "CONFIAVEL_NAO_OFICIAL", "desnivelMaximo": "CONFIAVEL_NAO_OFICIAL" }
  },

  {
    "marca": "Midea",
    "modelo": "Midea Xtreme Save Connect AGVCI R32 9000 BTU",
    "codigoBusca": ["42AGVCI09M5", "38AGVCI09M5", "42AGVCI09", "38AGVCI09", "AGVCI09", "MIDEA XTREME SAVE 9000"],
    "linha": "Xtreme Save Connect",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "9000 BTU/h",
    "tensao": "220V",
    "fluidoRefrigerante": "R32",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "manualInstalacao": "https://www.midea.com/content/dam/midea-aem/br/climatizacao/hiwall/xtreme-white-novo/Manual%20de%20usu%C3%A1rio_Xtreme%20Save%20Connect.pdf",
    "manualManutencao": "https://www.midea.com/content/dam/midea-aem/br/climatizacao/hiwall/xtreme-white-novo/Manual%20de%20usu%C3%A1rio_Xtreme%20Save%20Connect.pdf",
    "fonte": "Base tecnica HVAC PRO - Midea AGVCI09",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "tensao": "OFICIAL", "fluidoRefrigerante": "OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA" }
  },

  {
    "marca": "Midea",
    "modelo": "Midea Xtreme Save Connect AGVCI R32 12000 BTU",
    "codigoBusca": ["42AGVCI12M5", "38AGVCI12M5", "42AGVCI12", "38AGVCI12", "AGVCI12", "MIDEA XTREME SAVE 12000"],
    "linha": "Xtreme Save Connect",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "12000 BTU/h",
    "tensao": "220V",
    "fluidoRefrigerante": "R32",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "manualInstalacao": "https://www.midea.com/content/dam/midea-aem/br/climatizacao/hiwall/xtreme-white-novo/Manual%20de%20usu%C3%A1rio_Xtreme%20Save%20Connect.pdf",
    "manualManutencao": "https://www.midea.com/content/dam/midea-aem/br/climatizacao/hiwall/xtreme-white-novo/Manual%20de%20usu%C3%A1rio_Xtreme%20Save%20Connect.pdf",
    "fonte": "Base tecnica HVAC PRO - Midea AGVCI12",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "tensao": "OFICIAL", "fluidoRefrigerante": "OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA" }
  },

  {
    "marca": "Midea",
    "modelo": "Midea Xtreme Save Connect AGVCI R32 18000 BTU",
    "codigoBusca": ["42AGVCI18M5", "38AGVCI18M5", "42AGVCI18", "38AGVCI18", "AGVCI18", "MIDEA XTREME SAVE 18000"],
    "linha": "Xtreme Save Connect",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "18000 BTU/h",
    "tensao": "220V",
    "fluidoRefrigerante": "R32",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "manualInstalacao": "https://www.midea.com/content/dam/midea-aem/br/climatizacao/hiwall/xtreme-white-novo/Manual%20de%20usu%C3%A1rio_Xtreme%20Save%20Connect.pdf",
    "manualManutencao": "https://www.midea.com/content/dam/midea-aem/br/climatizacao/hiwall/xtreme-white-novo/Manual%20de%20usu%C3%A1rio_Xtreme%20Save%20Connect.pdf",
    "fonte": "Base tecnica HVAC PRO - Midea AGVCI18",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "tensao": "OFICIAL", "fluidoRefrigerante": "OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA" }
  },

  {
    "marca": "Midea",
    "modelo": "Midea Xtreme Save Connect AGVCI R32 24000 BTU",
    "codigoBusca": ["42AGVCI24M5", "38AGVCI24M5", "42AGVCI24", "38AGVCI24", "AGVCI24", "MIDEA XTREME SAVE 24000"],
    "linha": "Xtreme Save Connect",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "24000 BTU/h",
    "tensao": "220V",
    "fluidoRefrigerante": "R32",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "manualInstalacao": "https://www.midea.com/content/dam/midea-aem/br/climatizacao/hiwall/xtreme-white-novo/Manual%20de%20usu%C3%A1rio_Xtreme%20Save%20Connect.pdf",
    "manualManutencao": "https://www.midea.com/content/dam/midea-aem/br/climatizacao/hiwall/xtreme-white-novo/Manual%20de%20usu%C3%A1rio_Xtreme%20Save%20Connect.pdf",
    "fonte": "Base tecnica HVAC PRO - Midea AGVCI24",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "tensao": "OFICIAL", "fluidoRefrigerante": "OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA" }
  },

  {
    "marca": "Gree",
    "modelo": "Gree G-Diamond Auto Inverter R32 9000 BTU",
    "codigoBusca": ["GWC09ACA-D6DNA1A", "GWH09ACA-D6DNA1A", "G-DIAMOND 9000", "GREE 9000", "GREE 9000 R32"],
    "linha": "G-Diamond Auto Inverter",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "9000 BTU/h",
    "tensao": "220V / 60Hz / monofasico",
    "fluidoRefrigerante": "R32",
    "cargaGas": "550 g",
    "correnteNominal": "6 A",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "disjuntor": "Validar tabela do manual e instalacao local",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "tubulacaoAlta": "1/4 pol.",
    "tubulacaoBaixa": "3/8 pol.",
    "comprimentoMaximo": "15 m",
    "desnivelMaximo": "10 m",
    "manualInstalacao": "https://gree.com.br/wp-content/uploads/2025/02/Manual-G-DIAMOND-AUTO-INVERTER-Full.pdf",
    "manualManutencao": "https://gree.com.br/wp-content/uploads/2025/02/Manual-G-DIAMOND-AUTO-INVERTER-Full.pdf",
    "fonte": "Base tecnica HVAC PRO - Gree G-Diamond 9000",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL", "tensao": "CONFIAVEL_NAO_OFICIAL", "cargaGas": "CONFIAVEL_NAO_OFICIAL", "correnteNominal": "CONFIAVEL_NAO_OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "disjuntor": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA", "tubulacaoAlta": "CONFIAVEL_NAO_OFICIAL", "tubulacaoBaixa": "CONFIAVEL_NAO_OFICIAL", "comprimentoMaximo": "CONFIAVEL_NAO_OFICIAL", "desnivelMaximo": "CONFIAVEL_NAO_OFICIAL" }
  },

  {
    "marca": "Gree",
    "modelo": "Gree G-Diamond Auto Inverter R32 12000 BTU",
    "codigoBusca": ["GWC12ACC-D6DNA1A", "GWH12ACC-D6DNA1A", "G-DIAMOND 12000", "GREE 12000", "GREE 12000 R32"],
    "linha": "G-Diamond Auto Inverter",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "12000 BTU/h",
    "tensao": "220V / 60Hz / monofasico",
    "fluidoRefrigerante": "R32",
    "cargaGas": "630 g",
    "correnteNominal": "10,6 A",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "disjuntor": "Validar tabela do manual e instalacao local",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "tubulacaoAlta": "1/4 pol.",
    "tubulacaoBaixa": "1/2 pol.",
    "comprimentoMaximo": "20 m",
    "desnivelMaximo": "10 m",
    "manualInstalacao": "https://gree.com.br/wp-content/uploads/2025/02/Manual-G-DIAMOND-AUTO-INVERTER-Full.pdf",
    "manualManutencao": "https://gree.com.br/wp-content/uploads/2025/02/Manual-G-DIAMOND-AUTO-INVERTER-Full.pdf",
    "fonte": "Base tecnica HVAC PRO - Gree G-Diamond 12000",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL", "tensao": "CONFIAVEL_NAO_OFICIAL", "cargaGas": "CONFIAVEL_NAO_OFICIAL", "correnteNominal": "CONFIAVEL_NAO_OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "disjuntor": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA", "tubulacaoAlta": "CONFIAVEL_NAO_OFICIAL", "tubulacaoBaixa": "CONFIAVEL_NAO_OFICIAL", "comprimentoMaximo": "CONFIAVEL_NAO_OFICIAL", "desnivelMaximo": "CONFIAVEL_NAO_OFICIAL" }
  },

  {
    "marca": "Gree",
    "modelo": "Gree G-Diamond Auto Inverter R32 18000 BTU",
    "codigoBusca": ["GWC18ACD-D6DNA1C", "GWH18ACD-D6DNA1C", "G-DIAMOND 18000", "GREE 18000", "GREE 18000 R32"],
    "linha": "G-Diamond Auto Inverter",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "18000 BTU/h",
    "tensao": "220V / 60Hz / monofasico",
    "fluidoRefrigerante": "R32",
    "cargaGas": "940 g",
    "correnteNominal": "13,5 A",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "disjuntor": "Validar tabela do manual e instalacao local",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "tubulacaoAlta": "1/4 pol.",
    "tubulacaoBaixa": "1/2 pol.",
    "comprimentoMaximo": "25 m",
    "desnivelMaximo": "10 m",
    "manualInstalacao": "https://gree.com.br/wp-content/uploads/2025/02/Manual-G-DIAMOND-AUTO-INVERTER-Full.pdf",
    "manualManutencao": "https://gree.com.br/wp-content/uploads/2025/02/Manual-G-DIAMOND-AUTO-INVERTER-Full.pdf",
    "fonte": "Base tecnica HVAC PRO - Gree G-Diamond 18000",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL", "tensao": "CONFIAVEL_NAO_OFICIAL", "cargaGas": "CONFIAVEL_NAO_OFICIAL", "correnteNominal": "CONFIAVEL_NAO_OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "disjuntor": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA", "tubulacaoAlta": "CONFIAVEL_NAO_OFICIAL", "tubulacaoBaixa": "CONFIAVEL_NAO_OFICIAL", "comprimentoMaximo": "CONFIAVEL_NAO_OFICIAL", "desnivelMaximo": "CONFIAVEL_NAO_OFICIAL" }
  },

  {
    "marca": "Gree",
    "modelo": "Gree G-Diamond Auto Inverter R32 24000 BTU",
    "codigoBusca": ["GWC24ACE-D6DNA1B", "GWH24ACE-D6DNA1B", "G-DIAMOND 24000", "GREE 24000", "GREE 24000 R32"],
    "linha": "G-Diamond Auto Inverter",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "24000 BTU/h",
    "tensao": "220V / 60Hz / monofasico",
    "fluidoRefrigerante": "R32",
    "cargaGas": "1100 g",
    "correnteNominal": "13,5 A",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "disjuntor": "Validar tabela do manual e instalacao local",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "tubulacaoAlta": "1/4 pol.",
    "tubulacaoBaixa": "1/2 pol.",
    "comprimentoMaximo": "25 m",
    "desnivelMaximo": "10 m",
    "manualInstalacao": "https://gree.com.br/wp-content/uploads/2025/02/Manual-G-DIAMOND-AUTO-INVERTER-Full.pdf",
    "manualManutencao": "https://gree.com.br/wp-content/uploads/2025/02/Manual-G-DIAMOND-AUTO-INVERTER-Full.pdf",
    "fonte": "Base tecnica HVAC PRO - Gree G-Diamond 24000",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL", "tensao": "CONFIAVEL_NAO_OFICIAL", "cargaGas": "CONFIAVEL_NAO_OFICIAL", "correnteNominal": "CONFIAVEL_NAO_OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "disjuntor": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA", "tubulacaoAlta": "CONFIAVEL_NAO_OFICIAL", "tubulacaoBaixa": "CONFIAVEL_NAO_OFICIAL", "comprimentoMaximo": "CONFIAVEL_NAO_OFICIAL", "desnivelMaximo": "CONFIAVEL_NAO_OFICIAL" }
  },

  {
    "marca": "Gree",
    "modelo": "Gree G-Prime / G-Max / Cassete / Piso Teto - busca por linha",
    "codigoBusca": ["GREE G PRIME", "G-PRIME", "GREE G-MAX", "G-MAX", "GREE PISO TETO", "GREE CASSETE", "GREE CASSETTE", "GREE MULTISPLIT", "GREE MULTI SPLIT"],
    "linha": "G-Prime / G-Max / Comercial leve",
    "tipo": "Split / Piso Teto / Cassete / Multi Split conforme linha",
    "correnteTrabalho": "Variavel por modelo; validar etiqueta e manual especifico",
    "capacitor": "Validar esquema eletrico do modelo exato",
    "manualInstalacao": "https://gree.com.br/manuais/",
    "manualManutencao": "https://gree.com.br/manuais/",
    "fonte": "Base tecnica HVAC PRO - Gree linhas complementares",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA" }
  },

  {
    "marca": "LG",
    "modelo": "LG S4-Q12JA315 Dual Inverter Voice 12000 BTU Frio 220V",
    "codigoBusca": ["S4-Q12JA315", "S4Q12JA315", "LG S4-Q12JA315", "LG DUAL INVERTER VOICE 12000", "LG 12000 FRIO"],
    "linha": "Dual Inverter Voice",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "12000 BTU/h",
    "tensao": "220V",
    "fluidoRefrigerante": "R410A",
    "correnteNominal": "Validar etiqueta da unidade externa S4-Q12JA315",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "disjuntor": "Validar manual do codigo exato e instalacao local",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "tubulacaoAlta": "1/4 pol.",
    "tubulacaoBaixa": "3/8 pol.",
    "manualInstalacao": "https://www.lg.com/br/ar-condicionado-residencial/ar-condicionado-split/s4-q12ja315/",
    "manualManutencao": "https://www.lg.com/br/suporte/manuais-sistema/",
    "fonte": "Base tecnica HVAC PRO - LG S4-Q12JA315",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "tensao": "OFICIAL", "fluidoRefrigerante": "INFORMACAO_SUGERIDA", "correnteNominal": "INFORMACAO_SUGERIDA", "correnteTrabalho": "INFORMACAO_SUGERIDA", "disjuntor": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA", "tubulacaoAlta": "INFORMACAO_SUGERIDA", "tubulacaoBaixa": "INFORMACAO_SUGERIDA" }
  },

  {
    "marca": "LG",
    "modelo": "LG S4-W12JA31A Dual Inverter Voice 12000 BTU Quente Frio 220V",
    "codigoBusca": ["S4-W12JA31A", "S4W12JA31A", "LG S4-W12JA31A", "LG DUAL INVERTER VOICE QUENTE FRIO"],
    "linha": "Dual Inverter Voice",
    "tipo": "Split Hi Wall Inverter Quente/Frio",
    "capacidade": "12000 BTU/h",
    "tensao": "220V",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "manualInstalacao": "https://www.lg.com/br/ar-condicionado-residencial/ar-condicionado-residencial-inverter/s4-w12ja31a/",
    "manualManutencao": "https://www.lg.com/br/suporte/manuais-sistema/",
    "fonte": "Base tecnica HVAC PRO - LG S4-W12JA31A",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "tensao": "OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA" }
  },

  {
    "marca": "Samsung",
    "modelo": "Samsung AR12MVPXAWKNAZ WindFree 12000 BTU Frio",
    "codigoBusca": ["AR12MVPXAWKNAZ", "AR12MVPX", "AR12MVPXAWK", "SAMSUNG AR12MVPXAWKNAZ", "SAMSUNG WINDFREE 12000"],
    "linha": "WindFree",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "12000 BTU/h",
    "correnteNominal": "Validar etiqueta da unidade externa AR12MVPXAWKNAZ",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "disjuntor": "Validar manual do codigo exato e instalacao local",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "manualInstalacao": "https://www.samsung.com/br/support/model/AR12MVPXAWKNAZ/",
    "manualManutencao": "https://www.samsung.com/br/support/model/AR12MVPXAWKNAZ/",
    "fonte": "Base tecnica HVAC PRO - Samsung AR12MVPXAWKNAZ",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "correnteNominal": "INFORMACAO_SUGERIDA", "correnteTrabalho": "INFORMACAO_SUGERIDA", "disjuntor": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA" }
  },

  {
    "marca": "Samsung",
    "modelo": "Samsung AR12DYFABWKNAZ WindFree AI 12000 BTU Frio Wi-Fi",
    "codigoBusca": ["AR12DYFABWKNAZ", "AR12DYFAB", "AR12DYFABWK", "SAMSUNG AR12DYFABWKNAZ", "SAMSUNG WINDFREE AI 12000"],
    "linha": "WindFree AI",
    "tipo": "Split Hi Wall Inverter Wi-Fi",
    "capacidade": "12000 BTU/h",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "manualInstalacao": "https://www.samsung.com/br/support/model/AR12DYFABWKNAZ/",
    "manualManutencao": "https://www.samsung.com/br/support/model/AR12DYFABWKNAZ/",
    "fonte": "Base tecnica HVAC PRO - Samsung AR12DYFABWKNAZ",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA" }
  },

  {
    "marca": "Samsung",
    "modelo": "Samsung AR12DXFAAWKXAZ WindFree 12000 BTU",
    "codigoBusca": ["AR12DXFAAWKXAZ", "AR12DXFAA", "SAMSUNG AR12DXFAAWKXAZ", "SAMSUNG DXFA", "SAMSUNG WINDFREE 12000"],
    "linha": "WindFree",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "12000 BTU/h",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "manualInstalacao": "https://www.samsung.com/br/support/model/AR12DXFAAWKXAZ/",
    "manualManutencao": "https://www.samsung.com/br/support/model/AR12DXFAAWKXAZ/",
    "fonte": "Base tecnica HVAC PRO - Samsung AR12DXFAAWKXAZ",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA" }
  },

  {
    "marca": "Elgin",
    "modelo": "Elgin Eco Inverter II Wi-Fi HJFC09C2WBCB 9000 BTU Frio 220V",
    "codigoBusca": ["HJFC09C2WBCB", "HJFI09C2WB", "HJFE09C2CB", "ELGIN HJFC09", "ELGIN 9000 R32", "ELGIN 9000 FRIO"],
    "linha": "Eco Inverter II Wi-Fi",
    "tipo": "Split Hi Wall Inverter Frio",
    "capacidade": "9000 BTU/h",
    "tensao": "220V",
    "fluidoRefrigerante": "R32",
    "cargaGas": "Validar etiqueta da condensadora HJFE/HJFC 09",
    "correnteNominal": "7,3 A corrente maxima",
    "correnteTrabalho": "Inverter: medir em operacao estabilizada e comparar com etiqueta",
    "disjuntor": "10 A",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "tubulacaoAlta": "1/4 pol.",
    "tubulacaoBaixa": "3/8 pol.",
    "comprimentoMaximo": "15 m",
    "desnivelMaximo": "7 m",
    "manualInstalacao": "https://www.elgin.com.br/manuals",
    "manualManutencao": "https://www.elgin.com.br/manuals",
    "fonte": "Base tecnica HVAC PRO - Elgin Eco Inverter II 9000",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "tensao": "CONFIAVEL_NAO_OFICIAL", "fluidoRefrigerante": "CONFIAVEL_NAO_OFICIAL", "cargaGas": "INFORMACAO_SUGERIDA", "correnteNominal": "CONFIAVEL_NAO_OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "disjuntor": "CONFIAVEL_NAO_OFICIAL", "capacitor": "INFORMACAO_SUGERIDA", "tubulacaoAlta": "CONFIAVEL_NAO_OFICIAL", "tubulacaoBaixa": "CONFIAVEL_NAO_OFICIAL", "comprimentoMaximo": "CONFIAVEL_NAO_OFICIAL", "desnivelMaximo": "CONFIAVEL_NAO_OFICIAL" }
  },

  {
    "marca": "Elgin",
    "modelo": "Elgin Eco Inverter II Wi-Fi HJFC12C2WBCB 12000 BTU Frio 220V",
    "codigoBusca": ["HJFC12C2WBCB", "HJFI12C2WB", "HJFE12C2CB", "ELGIN HJFC12", "ELGIN 12000 R32", "ELGIN 12000 FRIO"],
    "linha": "Eco Inverter II Wi-Fi",
    "tipo": "Split Hi Wall Inverter Frio",
    "capacidade": "12000 BTU/h",
    "tensao": "220V",
    "fluidoRefrigerante": "R32",
    "cargaGas": "Validar etiqueta da condensadora HJFE/HJFC 12",
    "correnteNominal": "6,7 A corrente maxima",
    "correnteTrabalho": "Inverter: medir em operacao estabilizada e comparar com etiqueta",
    "disjuntor": "10 A",
    "capacitor": "Inverter: validar placa/diagrama do modelo exato",
    "tubulacaoAlta": "1/4 pol.",
    "tubulacaoBaixa": "3/8 pol.",
    "comprimentoMaximo": "15 m",
    "desnivelMaximo": "7 m",
    "manualInstalacao": "https://www.elgin.com.br/manuals",
    "manualManutencao": "https://www.elgin.com.br/manuals",
    "fonte": "Base tecnica HVAC PRO - Elgin Eco Inverter II 12000",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "tensao": "CONFIAVEL_NAO_OFICIAL", "fluidoRefrigerante": "CONFIAVEL_NAO_OFICIAL", "cargaGas": "INFORMACAO_SUGERIDA", "correnteNominal": "CONFIAVEL_NAO_OFICIAL", "correnteTrabalho": "INFORMACAO_SUGERIDA", "disjuntor": "CONFIAVEL_NAO_OFICIAL", "capacitor": "INFORMACAO_SUGERIDA", "tubulacaoAlta": "CONFIAVEL_NAO_OFICIAL", "tubulacaoBaixa": "CONFIAVEL_NAO_OFICIAL", "comprimentoMaximo": "CONFIAVEL_NAO_OFICIAL", "desnivelMaximo": "CONFIAVEL_NAO_OFICIAL" }
  },

  {
    "marca": "Komeco",
    "modelo": "Komeco KOHI09QC1HV Inverter 9000 BTU",
    "codigoBusca": ["KOHI09QC1HV", "KOHI 09QC 1HV", "KOHI 09", "KOMECO KOHI 09QC", "KOMECO 9000"],
    "linha": "KOHI Inverter",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "9000 BTU/h",
    "fluidoRefrigerante": "A2L baixa inflamabilidade conforme manual da linha",
    "cargaGas": "Validar etiqueta da unidade externa KOHI 09",
    "correnteNominal": "Validar etiqueta do conjunto KOHI09QC1HV",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "disjuntor": "Validar tabela eletrica do manual e instalacao local",
    "capacitor": "Inverter: validar manual tecnico/diagrama antes de substituir componente",
    "tubulacaoAlta": "Conforme tabela oficial da linha KOHI; validar modelo exato",
    "tubulacaoBaixa": "Conforme tabela oficial da linha KOHI; validar modelo exato",
    "manualInstalacao": "https://www.komeco.com.br/arquivos/manuais/ar-condicionado/split-hi-wall/manual-ar-condicionado-inverter-kohi.pdf",
    "manualManutencao": "https://www.komeco.com.br/portaltecnico/LINHA%20DE%20CONDICIONADORES%20DE%20AR/Manuais%20Tecnicos/MANUAL%20DE%20SERVICO%20INVERTER.PDF",
    "fonte": "Base tecnica HVAC PRO - Komeco KOHI 09",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL", "cargaGas": "INFORMACAO_SUGERIDA", "correnteNominal": "INFORMACAO_SUGERIDA", "correnteTrabalho": "INFORMACAO_SUGERIDA", "disjuntor": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA", "tubulacaoAlta": "OFICIAL", "tubulacaoBaixa": "OFICIAL" }
  },

  {
    "marca": "Komeco",
    "modelo": "Komeco KOHI12QC1HV Inverter 12000 BTU",
    "codigoBusca": ["KOHI12QC1HV", "KOHI 12QC 1HV", "KOHI 12", "KOMECO KOHI 12QC", "KOMECO 12000"],
    "linha": "KOHI Inverter",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "12000 BTU/h",
    "fluidoRefrigerante": "A2L baixa inflamabilidade conforme manual da linha",
    "cargaGas": "Validar etiqueta da unidade externa KOHI 12",
    "correnteNominal": "Validar etiqueta do conjunto KOHI12QC1HV",
    "correnteTrabalho": "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    "disjuntor": "Validar tabela eletrica do manual e instalacao local",
    "capacitor": "Inverter: validar manual tecnico/diagrama antes de substituir componente",
    "tubulacaoAlta": "Conforme tabela oficial da linha KOHI; validar modelo exato",
    "tubulacaoBaixa": "Conforme tabela oficial da linha KOHI; validar modelo exato",
    "manualInstalacao": "https://www.komeco.com.br/arquivos/manuais/ar-condicionado/split-hi-wall/manual-ar-condicionado-inverter-kohi.pdf",
    "manualManutencao": "https://www.komeco.com.br/portaltecnico/LINHA%20DE%20CONDICIONADORES%20DE%20AR/Manuais%20Tecnicos/MANUAL%20DE%20SERVICO%20INVERTER.PDF",
    "fonte": "Base tecnica HVAC PRO - Komeco KOHI 12",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL", "cargaGas": "INFORMACAO_SUGERIDA", "correnteNominal": "INFORMACAO_SUGERIDA", "correnteTrabalho": "INFORMACAO_SUGERIDA", "disjuntor": "INFORMACAO_SUGERIDA", "capacitor": "INFORMACAO_SUGERIDA", "tubulacaoAlta": "OFICIAL", "tubulacaoBaixa": "OFICIAL" }
  },

  {
    "marca": "Daikin",
    "modelo": "Daikin EcoSwing R32 FTKP12Q5VL / RKP12Q5VL 12000 BTU",
    "codigoBusca": ["FTKP12Q5VL", "RKP12Q5VL", "DAIKIN 12000", "DAIKIN ECOSWING 12000", "ECOSWING R32 12000"],
    "linha": "EcoSwing R-32",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "12000 BTU/h",
    "fluidoRefrigerante": "R32",
    "manualInstalacao": "https://www.daikin.com.br/profissionais/downloads",
    "manualManutencao": "https://www.daikin.com.br/profissionais/downloads",
    "fonte": "Base tecnica HVAC PRO - Daikin EcoSwing 12000",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL" }
  },

  {
    "marca": "Consul",
    "modelo": "Consul CBK12EBBCJ Dual Inverter Cobre Frio 12000 BTU",
    "codigoBusca": ["CBK12EBBCJ", "CBK12EB", "CONSUL CBK12EBBCJ", "CONSUL 12000", "CONSUL COBRE FRIO"],
    "linha": "Dual Inverter Cobre Frio",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "12000 BTU/h",
    "manualInstalacao": "https://www.consul.com.br/ar-condicionado-split-consul-dual-inverter-cobre-frio-12000-btus-cbk12eb/p",
    "manualManutencao": "https://www.consul.com.br/atendimento/perguntas-frequentes/problemas-com-o-produto/manual-de-instrucoes-como-encontrar",
    "fonte": "Base tecnica HVAC PRO - Consul CBK12EBBCJ",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL" }
  },

  {
    "marca": "Electrolux",
    "modelo": "Electrolux QI12F / QE12F Inverter Split 12000 BTU Frio 220V",
    "codigoBusca": ["QI12F", "QE12F", "QI12F/QE12F", "ELECTROLUX QI12F", "ELECTROLUX QE12F", "ELECTROLUX 12000 FRIO"],
    "linha": "Split Inverter",
    "tipo": "Split Hi Wall Inverter Frio",
    "capacidade": "12000 BTU/h",
    "tensao": "220V",
    "manualInstalacao": "https://loja.electrolux.com.br/ar-condicionado-split-electrolux-inverter-12000-btus-frio-qi12f-qe12f/p",
    "manualManutencao": "https://cuida.electrolux.com.br/guias-e-manuais",
    "fonte": "Base tecnica HVAC PRO - Electrolux QI12F QE12F",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "tensao": "OFICIAL" }
  },

  {
    "marca": "Philco",
    "modelo": "Philco PAC12QA Inverter Espelhado 12000 BTU Quente Frio R32",
    "codigoBusca": ["PAC12QA", "PHILCO PAC12QA", "PHILCO ESPELHADO", "PHILCO R32", "PHILCO 12000"],
    "linha": "Inverter Espelhado",
    "tipo": "Split Hi Wall Inverter Quente/Frio",
    "capacidade": "12000 BTU/h",
    "fluidoRefrigerante": "R32",
    "manualInstalacao": "https://www.philco.com.br/climatizacao/ar-condicionado/Inverter?PS=20&map=c%2Cc%2CspecificationFilter_191",
    "manualManutencao": "https://www.philco.com.br/climatizacao/ar-condicionado/Inverter?PS=20&map=c%2Cc%2CspecificationFilter_191",
    "fonte": "Base tecnica HVAC PRO - Philco PAC12QA",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL" }
  },

  {
    "marca": "Britania",
    "modelo": "Britania Prime Air Inverter 12QC 12000 BTU Quente Frio",
    "codigoBusca": ["12QC", "BRITANIA 12QC", "BRITÂNIA 12QC", "PRIME AIR 12QC", "BRITANIA 12000"],
    "linha": "Prime Air Split Inverter",
    "tipo": "Split Hi Wall Inverter Quente/Frio",
    "capacidade": "12000 BTU/h",
    "fluidoRefrigerante": "R32",
    "manualInstalacao": "https://www.britania.com.br/ar-condicionado-prime-air-inverter-12000btus-quente-frio-12qc/p",
    "manualManutencao": "https://www.britania.com.br/ar-condicionado-prime-air-inverter-12000btus-quente-frio-12qc/p",
    "fonte": "Base tecnica HVAC PRO - Britania Prime Air 12QC",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL" }
  },

  {
    "marca": "TCL",
    "modelo": "TCL Serie A2 Inverter TAC-09CSA2-INV 9000 BTU",
    "codigoBusca": ["TAC-09CSA2-INV", "TAC09CSA2INV", "TCL A2 9000", "TCL 9000", "TCL INVERTER 9000"],
    "linha": "Serie A2 Inverter",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "9000 BTU/h",
    "manualInstalacao": "https://www.tcl.com/br/pt/air-conditioners/series-a2-inverter",
    "manualManutencao": "https://www.tcl.com/br/pt/air-conditioners/series-a2-inverter",
    "fonte": "Base tecnica HVAC PRO - TCL Serie A2 9000",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL" }
  },

  {
    "marca": "Agratto",
    "modelo": "Agratto LIV Inverter TOP LCST12F-02I 12000 BTU Frio",
    "codigoBusca": ["LCST12F-02I", "LCST12F02I", "AGRATTO LIV 12000", "AGRATTO 12000", "AGRATTO SPLIT INVERTER"],
    "linha": "LIV Inverter TOP",
    "tipo": "Split Hi Wall Inverter Frio",
    "capacidade": "12000 BTU/h",
    "tensao": "220V",
    "manualInstalacao": "https://www.agratto.com.br/ar-condicionado/residencial/liv",
    "manualManutencao": "https://www.agratto.com.br/ar-condicionado/residencial/liv",
    "fonte": "Base tecnica HVAC PRO - Agratto LIV 12000",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "tensao": "OFICIAL" }
  },

  {
    "marca": "Hitachi",
    "modelo": "Hitachi airHome 600 SPK09C3IVF 9000 BTU",
    "codigoBusca": ["SPK09C3IVF", "RPK09C3IVF", "RAA09C3IVF", "HITACHI 9000", "AIRHOME 600 9000"],
    "linha": "airHome 600",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "9000 BTU/h",
    "fluidoRefrigerante": "R32",
    "manualInstalacao": "https://documentation.hitachiaircon.com/br/pt/rac/spk-c3iv-f-q",
    "manualManutencao": "https://documentation.hitachiaircon.com/br/pt/rac/spk-c3iv-f-q",
    "fonte": "Base tecnica HVAC PRO - Hitachi airHome 600 9000",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL" }
  },

  {
    "marca": "Hitachi",
    "modelo": "Hitachi airHome 600 SPK12C3IVF 12000 BTU",
    "codigoBusca": ["SPK12C3IVF", "RPK12C3IVF", "RAA12C3IVF", "HITACHI 12000", "AIRHOME 600 12000"],
    "linha": "airHome 600",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "12000 BTU/h",
    "fluidoRefrigerante": "R32",
    "manualInstalacao": "https://documentation.hitachiaircon.com/br/pt/rac/spk-c3iv-f-q",
    "manualManutencao": "https://documentation.hitachiaircon.com/br/pt/rac/spk-c3iv-f-q",
    "fonte": "Base tecnica HVAC PRO - Hitachi airHome 600 12000",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL" }
  },

  {
    "marca": "Hitachi",
    "modelo": "Hitachi airHome 600 SPK18C3IVF 18000 BTU",
    "codigoBusca": ["SPK18C3IVF", "RPK18C3IVF", "RAA18C3IVF", "HITACHI 18000", "AIRHOME 600 18000"],
    "linha": "airHome 600",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "18000 BTU/h",
    "fluidoRefrigerante": "R32",
    "manualInstalacao": "https://documentation.hitachiaircon.com/br/pt/rac/spk-c3iv-f-q",
    "manualManutencao": "https://documentation.hitachiaircon.com/br/pt/rac/spk-c3iv-f-q",
    "fonte": "Base tecnica HVAC PRO - Hitachi airHome 600 18000",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL" }
  },

  {
    "marca": "Hitachi",
    "modelo": "Hitachi airHome 600 SPK24C3IVF 24000 BTU",
    "codigoBusca": ["SPK24C3IVF", "RPK24C3IVF", "RAA24C3IVF", "HITACHI 24000", "AIRHOME 600 24000"],
    "linha": "airHome 600",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "24000 BTU/h",
    "fluidoRefrigerante": "R32",
    "manualInstalacao": "https://documentation.hitachiaircon.com/br/pt/rac/spk-c3iv-f-q",
    "manualManutencao": "https://documentation.hitachiaircon.com/br/pt/rac/spk-c3iv-f-q",
    "fonte": "Base tecnica HVAC PRO - Hitachi airHome 600 24000",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL" }
  },

  {
    "marca": "Hisense",
    "modelo": "Hisense Split Hi-Smart Inverter - busca por linha",
    "codigoBusca": ["HISENSE", "HISENSE SPLIT", "HISENSE INVERTER", "HISENSE AR CONDICIONADO", "HI SMART", "HI-SMART", "HISENSE HI SMART"],
    "linha": "Hi-Smart Inverter",
    "tipo": "Split Hi Wall Inverter",
    "manualInstalacao": "https://www.hisense.com.br/ar-condicionado/split-hi-smart/",
    "manualManutencao": "https://www.hisense.com.br/ar-condicionado/split-hi-smart/",
    "fonte": "Base tecnica HVAC PRO - Hisense Hi-Smart",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL" }
  },

  {
    "marca": "EOS",
    "modelo": "EOS Master Inverter R32 - busca por linha",
    "codigoBusca": ["EOS", "EOS MASTER INVERTER", "MASTER INVERTER EOS", "EOS R32", "EOS 9000", "EOS 12000", "EOS 18000", "EOS 24000", "EOS 30000"],
    "linha": "Master Inverter",
    "tipo": "Split Hi Wall Inverter",
    "capacidade": "9000 / 12000 / 18000 / 24000 / 30000 BTU/h conforme modelo",
    "fluidoRefrigerante": "R32",
    "manualInstalacao": "https://eos.com.br/ar-condicionado-eos-master-inverter/",
    "manualManutencao": "https://eos.com.br/downloads/",
    "fonte": "Base tecnica HVAC PRO - EOS Master Inverter",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL", "fluidoRefrigerante": "OFICIAL" }
  },

  {
    "marca": "Fujitsu / General",
    "modelo": "Fujitsu General Split High Wall - busca por linha",
    "codigoBusca": ["FUJITSU", "GENERAL", "FUJITSU GENERAL", "SPLIT HIGH WALL FUJITSU", "HIGH WALL GENERAL", "FUJITSU PREMIUM", "GENERAL PREMIUM", "FUJITSU 9000", "FUJITSU 12000"],
    "linha": "Split High Wall / Airstage",
    "tipo": "Split Hi Wall / Multi Split / VRF conforme linha",
    "manualInstalacao": "https://www.fujitsu-general.com/br/products/split/wall/index.html?page=1&pagemax=30",
    "manualManutencao": "https://www.fujitsu-general.com/br/products/split/",
    "fonte": "Base tecnica HVAC PRO - Fujitsu General",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL" }
  },

  {
    "marca": "Springer Midea / Carrier",
    "modelo": "Springer Midea AirVolution Connect - busca por linha",
    "codigoBusca": ["SPRINGER", "SPRINGER MIDEA", "CARRIER", "AIRVOLUTION", "AIR VOLUTION", "AIRVOLUTION CONNECT", "MIDEA AIRVOLUTION"],
    "linha": "AirVolution Connect / Carrier legado",
    "tipo": "Split Hi Wall / Piso Teto / Cassete conforme modelo",
    "manualInstalacao": "https://conteudo.midea.com.br/manuais/ar-condicionado-12000-btu-springer-midea-airvolution-connect-quente-e-frio.pdf",
    "manualManutencao": "https://conteudo.midea.com.br/manuais/ar-condicionado-12000-btu-springer-midea-airvolution-connect-quente-e-frio.pdf",
    "fonte": "Base tecnica HVAC PRO - Springer Midea Carrier",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL" }
  },

  {
    "marca": "Trane",
    "modelo": "Trane Multi Split / Comercial Leve - busca por linha",
    "codigoBusca": ["TRANE", "TRANE MULTI SPLIT", "MULTI SPLIT INVERTER TRANE", "4MDC", "4MWC", "TRANE R410A", "TRANE VRF", "TRANE ROOFTOP", "TRANE CHILLER"],
    "linha": "Multi Split / Comercial",
    "tipo": "Multi Split / VRF / Rooftop / Chiller conforme linha",
    "fluidoRefrigerante": "R-410A conforme linha",
    "manualInstalacao": "https://trane.com.br/commercial/latin-america/br/pt/produtos-trane.html",
    "manualManutencao": "https://trane.com.br/commercial/latin-america/br/pt/produtos-trane.html",
    "fonte": "Base tecnica HVAC PRO - Trane",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "fluidoRefrigerante": "OFICIAL" }
  },

  {
    "marca": "Olimpia Splendid",
    "modelo": "Olimpia Splendid Portatil Dolceclima - busca por linha",
    "codigoBusca": ["OLIMPIA", "OLIMPIA SPLENDID", "OLIMPIA PORTATIL", "OLIMPIA PORTÁTIL", "PORTATIL OLIMPIA", "PORTÁTIL OLIMPIA", "DOLCECLIMA", "DOLCE CLIMA"],
    "linha": "Portatil / Dolceclima",
    "tipo": "Ar-condicionado portatil",
    "manualInstalacao": "https://www.olimpiasplendid.com.br/area_download",
    "manualManutencao": "https://www.olimpiasplendid.com.br/area_download",
    "fonte": "Base tecnica HVAC PRO - Olimpia Splendid Portatil",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL" }
  },

  {
    "marca": "York / Johnson Controls",
    "modelo": "York Split Hi Wall Everest - busca por linha",
    "codigoBusca": ["YORK", "JOHNSON CONTROLS", "YORK EVEREST", "EVEREST", "RAEA", "RADA", "RAKA", "RAJA", "YORK HI WALL", "YORK SPLIT"],
    "linha": "Everest / Split Hi Wall legado",
    "tipo": "Split Hi Wall",
    "manualInstalacao": "https://pdf.webarcondicionado.com.br/york/manual/usuario/mdu-split-hi-wall-raea-rada-raka-raja-everest.pdf",
    "manualManutencao": "https://digital.johnsoncontrols.com/brasilhvac",
    "fonte": "Base tecnica HVAC PRO - York Everest",
    "fonteTipo": "CONFIAVEL_NAO_OFICIAL",
    "nivelConfianca": "CONFIAVEL_NAO_OFICIAL",
    "status": "CONFIAVEL_NAO_OFICIAL",
    "confiancaCampos": { "marca": "CONFIAVEL_NAO_OFICIAL", "modelo": "CONFIAVEL_NAO_OFICIAL", "linha": "CONFIAVEL_NAO_OFICIAL", "tipo": "CONFIAVEL_NAO_OFICIAL" }
  },

  {
    "marca": "Mitsubishi Electric",
    "modelo": "Mitsubishi Electric Mr Slim / City Multi - busca por linha",
    "codigoBusca": ["MITSUBISHI", "MITSUBISHI ELECTRIC", "MITSUBISHI AR CONDICIONADO", "MITSUBISHI SPLIT", "MITSUBISHI VRF", "MITSUBISHI CITY MULTI", "CITY MULTI", "MR SLIM", "MITSUBISHI MR SLIM", "MSZ", "MUZ", "MSY", "MUY"],
    "linha": "Mr Slim / City Multi / Split / VRF",
    "tipo": "Split / Multi Split / VRF conforme linha",
    "manualInstalacao": "https://br.mitsubishielectric.com/pt/products-solutions/",
    "manualManutencao": "https://br.mitsubishielectric.com/pt/products-solutions/",
    "fonte": "Base tecnica HVAC PRO - Mitsubishi Electric",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL" }
  },

  {
    "marca": "Rheem",
    "modelo": "Rheem Multi Split / Split Hi Wall - busca por linha",
    "codigoBusca": ["RHEEM", "RHEEM SPLIT", "RHEEM MULTI SPLIT", "RHEEM MULTISPLIT", "RHEEM INVERTER", "RHEEM HI WALL", "RHEEM 9000", "RHEEM 12000", "RHEEM 18000", "RHEEM 24000"],
    "linha": "Split / Multi Split",
    "tipo": "Split Hi Wall / Multi Split conforme modelo",
    "manualInstalacao": "https://www.rheem.com.br/manuais/",
    "manualManutencao": "https://www.rheem.com.br/manuais/",
    "fonte": "Base tecnica HVAC PRO - Rheem Manuais",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL" }
  },

  {
    "marca": "Comfee",
    "modelo": "Comfee Split Hi Wall 12000 BTU Frio",
    "codigoBusca": ["COMFEE", "COMFEE SPLIT", "COMFEE HI WALL", "COMFEE 12000", "COMFEE FRIO", "COMFEE MIDEA", "42AFVC", "38AFVC", "42AFCB", "42AFCD", "38KCW"],
    "linha": "Split Hi Wall Comfee",
    "tipo": "Split Hi Wall",
    "capacidade": "12000 BTU/h",
    "manualInstalacao": "https://www.midea.com/content/dam/midea-aem/br/climatizacao/hiwall/split-high-wall-comfee-12000-btu-h-frio/Manual-do-Propriet-rio-Split-Hi-Wall-Comfee.pdf",
    "manualManutencao": "https://www.midea.com/content/dam/midea-aem/br/climatizacao/hiwall/split-high-wall-comfee-12000-btu-h-frio/Manual-do-Propriet-rio-Split-Hi-Wall-Comfee.pdf",
    "fonte": "Base tecnica HVAC PRO - Comfee Split Hi Wall",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "capacidade": "OFICIAL" }
  },

  {
    "marca": "Fontaine",
    "modelo": "Fontaine Split Hi Wall - busca por linha",
    "codigoBusca": ["FONTAINE", "FONTAINE BRASIL", "FONTAINE SPLIT", "FONTAINE HI WALL", "FONTAINE 127V", "FONTAINE 220V", "FONTAINE 9000", "FONTAINE 12000", "FONTAINE 18000", "FONTAINE 24000"],
    "linha": "Split Hi Wall Fontaine",
    "tipo": "Split Hi Wall",
    "tensao": "127V / 220V conforme modelo",
    "manualInstalacao": "https://fontainebrasil.com.br/",
    "manualManutencao": "https://fontainebrasil.com.br/",
    "fonte": "Base tecnica HVAC PRO - Fontaine Brasil",
    "fonteTipo": "FABRICANTE_OFICIAL",
    "nivelConfianca": "OFICIAL",
    "status": "OFICIAL",
    "confiancaCampos": { "marca": "OFICIAL", "modelo": "OFICIAL", "linha": "OFICIAL", "tipo": "OFICIAL", "tensao": "OFICIAL" }
  }
];
