window.acervoTecnico = [
  {
    marca: "Philco",
    modelo: "Philco PAC12QC Split Inverter 12000 BTU",
    codigoBusca: ["PAC12QC", "PHILCO PAC12QC", "PHILCO SPLIT INVERTER 12000", "PHILCO 12000"],
    linha: "Split Inverter",
    tipo: "Split Hi Wall Inverter",
    capacidade: "12000 BTU/h",
    correnteTrabalho: "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    observacaoTecnica: "Validar fluido, carga, disjuntor e tubulacao na etiqueta da condensadora.",
    manualInstalacao: "https://www.philco.com.br/ar-condicionado-split-12000-pac12qc/p",
    manualManutencao: "https://www.philco.com.br/ar-condicionado-split-12000-pac12qc/p",
    fonte: "Base tecnica HVAC PRO - Philco PAC12QC",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA",
      observacaoTecnica: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "Britania",
    modelo: "Britania Prime Air Inverter 12QC 12000 BTU Quente Frio",
    codigoBusca: ["12QC", "BRITANIA 12QC", "BRITÂNIA 12QC", "PRIME AIR 12QC", "BRITANIA 12000", "BRITÂNIA 12000"],
    linha: "Prime Air Split Inverter",
    tipo: "Split Hi Wall Inverter Quente/Frio",
    capacidade: "12000 BTU/h",
    fluidoRefrigerante: "R32",
    correnteTrabalho: "Inverter: corrente varia por rotacao e carga termica",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    manualInstalacao: "https://www.britania.com.br/ar-condicionado-prime-air-inverter-12000btus-quente-frio-12qc/p",
    manualManutencao: "https://www.britania.com.br/ar-condicionado-prime-air-inverter-12000btus-quente-frio-12qc/p",
    fonte: "Base tecnica HVAC PRO - Britania Prime Air 12QC",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      fluidoRefrigerante: "OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "TCL",
    modelo: "TCL Serie A2 Inverter TAC-09CSA2-INV 9000 BTU",
    codigoBusca: ["TAC-09CSA2-INV", "TAC09CSA2INV", "TCL A2 9000", "TCL 9000", "TCL INVERTER 9000"],
    linha: "Serie A2 Inverter",
    tipo: "Split Hi Wall Inverter",
    capacidade: "9000 BTU/h",
    correnteTrabalho: "Inverter: corrente varia conforme carga termica e modo de operacao",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    manualInstalacao: "https://www.tcl.com/br/pt/air-conditioners/series-a2-inverter",
    manualManutencao: "https://www.tcl.com/br/pt/air-conditioners/series-a2-inverter",
    fonte: "Base tecnica HVAC PRO - TCL Serie A2 9000",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "TCL",
    modelo: "TCL Serie A2 Inverter TAC-12CSA2-INV 12000 BTU",
    codigoBusca: ["TAC-12CSA2-INV", "TAC12CSA2INV", "TCL A2 12000", "TCL 12000", "TCL INVERTER 12000"],
    linha: "Serie A2 Inverter",
    tipo: "Split Hi Wall Inverter",
    capacidade: "12000 BTU/h",
    correnteTrabalho: "Inverter: corrente varia conforme carga termica e modo de operacao",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    manualInstalacao: "https://www.tcl.com/br/pt/air-conditioners/series-a2-inverter",
    manualManutencao: "https://www.tcl.com/br/pt/air-conditioners/series-a2-inverter",
    fonte: "Base tecnica HVAC PRO - TCL Serie A2 12000",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "TCL",
    modelo: "TCL Serie A2 Inverter TAC-18CSA2-INV 18000 BTU",
    codigoBusca: ["TAC-18CSA2-INV", "TAC18CSA2INV", "TCL A2 18000", "TCL 18000", "TCL INVERTER 18000"],
    linha: "Serie A2 Inverter",
    tipo: "Split Hi Wall Inverter",
    capacidade: "18000 BTU/h",
    correnteTrabalho: "Inverter: corrente varia conforme carga termica e modo de operacao",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    manualInstalacao: "https://www.tcl.com/br/pt/air-conditioners/series-a2-inverter",
    manualManutencao: "https://www.tcl.com/br/pt/air-conditioners/series-a2-inverter",
    fonte: "Base tecnica HVAC PRO - TCL Serie A2 18000",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "Agratto",
    modelo: "Agratto LIV Inverter TOP LCST09F 9000 BTU Frio",
    codigoBusca: ["LCST09F", "LCST09F-02I", "LCST09F02I", "AGRATTO LIV 9000", "AGRATTO 9000", "AGRATTO INVERTER 9000"],
    linha: "LIV Inverter TOP",
    tipo: "Split Hi Wall Inverter Frio",
    capacidade: "9000 BTU/h",
    correnteTrabalho: "Inverter: corrente varia por carga termica e modo de operacao",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    manualInstalacao: "https://www.agratto.com.br/ar-condicionado/residencial/liv",
    manualManutencao: "https://www.agratto.com.br/ar-condicionado/residencial/liv",
    fonte: "Base tecnica HVAC PRO - Agratto LIV 9000",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "Agratto",
    modelo: "Agratto LIV Inverter TOP LCST12F-02I 12000 BTU Frio",
    codigoBusca: ["LCST12F", "LCST12F-02I", "LCST12F02I", "AGRATTO LIV 12000", "AGRATTO 12000", "AGRATTO INVERTER 12000"],
    linha: "LIV Inverter TOP",
    tipo: "Split Hi Wall Inverter Frio",
    capacidade: "12000 BTU/h",
    tensao: "220V",
    correnteTrabalho: "Inverter: corrente varia por carga termica e modo de operacao",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    manualInstalacao: "https://www.agratto.com.br/ar-condicionado/residencial/liv",
    manualManutencao: "https://www.agratto.com.br/ar-condicionado/residencial/liv",
    fonte: "Base tecnica HVAC PRO - Agratto LIV 12000",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      tensao: "OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "Agratto",
    modelo: "Agratto LIV Inverter TOP LCST18F 18000 BTU Frio",
    codigoBusca: ["LCST18F", "LCST18F-02I", "LCST18F02I", "AGRATTO LIV 18000", "AGRATTO 18000", "AGRATTO INVERTER 18000"],
    linha: "LIV Inverter TOP",
    tipo: "Split Hi Wall Inverter Frio",
    capacidade: "18000 BTU/h",
    correnteTrabalho: "Inverter: corrente varia por carga termica e modo de operacao",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    manualInstalacao: "https://www.agratto.com.br/ar-condicionado/residencial/liv",
    manualManutencao: "https://www.agratto.com.br/ar-condicionado/residencial/liv",
    fonte: "Base tecnica HVAC PRO - Agratto LIV 18000",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "Midea",
    modelo: "Midea Xtreme Save AI Connect AGVCJ R32 9000 BTU",
    codigoBusca: ["42AGVCJ09M5", "38AGVCJ09M5", "42AGVCJ09", "38AGVCJ09", "AGVCJ09", "MIDEA 9000 R32", "XTREME SAVE AI CONNECT 9000"],
    linha: "Xtreme Save AI Connect",
    tipo: "Split Hi Wall Inverter Frio",
    capacidade: "9000 BTU/h",
    tensao: "220V",
    fluidoRefrigerante: "R32",
    cargaGas: "320 g ate 5 m",
    correnteNominal: "Validar etiqueta da unidade externa 38AGVCJ09M5",
    correnteTrabalho: "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    disjuntor: "Validar tabela do manual e instalacao eletrica local",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    tubulacaoAlta: "1/4 pol.",
    tubulacaoBaixa: "3/8 pol.",
    comprimentoMaximo: "25 m",
    desnivelMaximo: "10 m",
    manualInstalacao: "https://conteudo.midea.com.br/manuais/Ar-Condicionado-Midea-Inverter-Xtreme-Save-AI-Connect.pdf",
    manualManutencao: "https://conteudo.midea.com.br/manuais/Ar-Condicionado-Midea-Inverter-Xtreme-Save-AI-Connect.pdf",
    fonte: "Base tecnica HVAC PRO - Midea AGVCJ09",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      tensao: "OFICIAL",
      fluidoRefrigerante: "OFICIAL",
      cargaGas: "CONFIAVEL_NAO_OFICIAL",
      correnteNominal: "INFORMACAO_SUGERIDA",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      disjuntor: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA",
      tubulacaoAlta: "CONFIAVEL_NAO_OFICIAL",
      tubulacaoBaixa: "CONFIAVEL_NAO_OFICIAL",
      comprimentoMaximo: "CONFIAVEL_NAO_OFICIAL",
      desnivelMaximo: "CONFIAVEL_NAO_OFICIAL"
    }
  },

  {
    marca: "Midea",
    modelo: "Midea Xtreme Save AI Connect AGVCJ R32 12000 BTU",
    codigoBusca: ["42AGVCJ12M5", "38AGVCJ12M5", "42AGVCJ12", "38AGVCJ12", "AGVCJ12", "MIDEA 12000 R32", "XTREME SAVE AI CONNECT 12000"],
    linha: "Xtreme Save AI Connect",
    tipo: "Split Hi Wall Inverter Frio",
    capacidade: "12000 BTU/h",
    tensao: "220V",
    fluidoRefrigerante: "R32",
    cargaGas: "440 g ate 5 m",
    correnteNominal: "Validar etiqueta da unidade externa 38AGVCJ12M5",
    correnteTrabalho: "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    disjuntor: "Validar tabela do manual e instalacao eletrica local",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    tubulacaoAlta: "1/4 pol.",
    tubulacaoBaixa: "3/8 pol.",
    comprimentoMaximo: "25 m",
    desnivelMaximo: "10 m",
    manualInstalacao: "https://conteudo.midea.com.br/manuais/Ar-Condicionado-Midea-Inverter-Xtreme-Save-AI-Connect.pdf",
    manualManutencao: "https://conteudo.midea.com.br/manuais/Ar-Condicionado-Midea-Inverter-Xtreme-Save-AI-Connect.pdf",
    fonte: "Base tecnica HVAC PRO - Midea AGVCJ12",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      tensao: "OFICIAL",
      fluidoRefrigerante: "OFICIAL",
      cargaGas: "CONFIAVEL_NAO_OFICIAL",
      correnteNominal: "INFORMACAO_SUGERIDA",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      disjuntor: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA",
      tubulacaoAlta: "CONFIAVEL_NAO_OFICIAL",
      tubulacaoBaixa: "CONFIAVEL_NAO_OFICIAL",
      comprimentoMaximo: "CONFIAVEL_NAO_OFICIAL",
      desnivelMaximo: "CONFIAVEL_NAO_OFICIAL"
    }
  },

  {
    marca: "Gree",
    modelo: "Gree G-Diamond Auto Inverter R32 9000 BTU",
    codigoBusca: ["GWC09ACA-D6DNA1A", "GWH09ACA-D6DNA1A", "G-DIAMOND 9000", "GREE 9000", "GREE 9000 R32"],
    linha: "G-Diamond Auto Inverter",
    tipo: "Split Hi Wall Inverter",
    capacidade: "9000 BTU/h",
    tensao: "220V / 60Hz / monofasico",
    fluidoRefrigerante: "R32",
    cargaGas: "550 g",
    correnteNominal: "6 A",
    correnteTrabalho: "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    disjuntor: "Validar tabela do manual e instalacao local",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    tubulacaoAlta: "1/4 pol.",
    tubulacaoBaixa: "3/8 pol.",
    comprimentoMaximo: "15 m",
    desnivelMaximo: "10 m",
    manualInstalacao: "https://gree.com.br/wp-content/uploads/2025/02/Manual-G-DIAMOND-AUTO-INVERTER-Full.pdf",
    manualManutencao: "https://gree.com.br/wp-content/uploads/2025/02/Manual-G-DIAMOND-AUTO-INVERTER-Full.pdf",
    fonte: "Base tecnica HVAC PRO - Gree G-Diamond 9000",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      fluidoRefrigerante: "OFICIAL",
      tensao: "CONFIAVEL_NAO_OFICIAL",
      cargaGas: "CONFIAVEL_NAO_OFICIAL",
      correnteNominal: "CONFIAVEL_NAO_OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      disjuntor: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA",
      tubulacaoAlta: "CONFIAVEL_NAO_OFICIAL",
      tubulacaoBaixa: "CONFIAVEL_NAO_OFICIAL",
      comprimentoMaximo: "CONFIAVEL_NAO_OFICIAL",
      desnivelMaximo: "CONFIAVEL_NAO_OFICIAL"
    }
  },

  {
    marca: "Gree",
    modelo: "Gree G-Diamond Auto Inverter R32 12000 BTU",
    codigoBusca: ["GWC12ACC-D6DNA1A", "GWH12ACC-D6DNA1A", "G-DIAMOND 12000", "GREE 12000", "GREE 12000 R32"],
    linha: "G-Diamond Auto Inverter",
    tipo: "Split Hi Wall Inverter",
    capacidade: "12000 BTU/h",
    tensao: "220V / 60Hz / monofasico",
    fluidoRefrigerante: "R32",
    cargaGas: "630 g",
    correnteNominal: "10,6 A",
    correnteTrabalho: "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    disjuntor: "Validar tabela do manual e instalacao local",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    tubulacaoAlta: "1/4 pol.",
    tubulacaoBaixa: "1/2 pol.",
    comprimentoMaximo: "20 m",
    desnivelMaximo: "10 m",
    manualInstalacao: "https://gree.com.br/wp-content/uploads/2025/02/Manual-G-DIAMOND-AUTO-INVERTER-Full.pdf",
    manualManutencao: "https://gree.com.br/wp-content/uploads/2025/02/Manual-G-DIAMOND-AUTO-INVERTER-Full.pdf",
    fonte: "Base tecnica HVAC PRO - Gree G-Diamond 12000",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      fluidoRefrigerante: "OFICIAL",
      tensao: "CONFIAVEL_NAO_OFICIAL",
      cargaGas: "CONFIAVEL_NAO_OFICIAL",
      correnteNominal: "CONFIAVEL_NAO_OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      disjuntor: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA",
      tubulacaoAlta: "CONFIAVEL_NAO_OFICIAL",
      tubulacaoBaixa: "CONFIAVEL_NAO_OFICIAL",
      comprimentoMaximo: "CONFIAVEL_NAO_OFICIAL",
      desnivelMaximo: "CONFIAVEL_NAO_OFICIAL"
    }
  },

  {
    marca: "LG",
    modelo: "LG S4-Q12JA315 Dual Inverter Voice 12000 BTU Frio 220V",
    codigoBusca: ["S4-Q12JA315", "S4Q12JA315", "LG S4-Q12JA315", "LG DUAL INVERTER VOICE 12000", "LG 12000 FRIO"],
    linha: "Dual Inverter Voice",
    tipo: "Split Hi Wall Inverter",
    capacidade: "12000 BTU/h",
    tensao: "220V",
    fluidoRefrigerante: "R410A",
    correnteNominal: "Validar etiqueta da unidade externa S4-Q12JA315",
    correnteTrabalho: "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    disjuntor: "Validar manual do codigo exato e instalacao local",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    tubulacaoAlta: "1/4 pol.",
    tubulacaoBaixa: "3/8 pol.",
    manualInstalacao: "https://www.lg.com/br/ar-condicionado-residencial/ar-condicionado-split/s4-q12ja315/",
    manualManutencao: "https://www.lg.com/br/suporte/manuais-sistema/",
    fonte: "Base tecnica HVAC PRO - LG S4-Q12JA315",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      tensao: "OFICIAL",
      fluidoRefrigerante: "INFORMACAO_SUGERIDA",
      correnteNominal: "INFORMACAO_SUGERIDA",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      disjuntor: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA",
      tubulacaoAlta: "INFORMACAO_SUGERIDA",
      tubulacaoBaixa: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "Samsung",
    modelo: "Samsung AR12MVPXAWKNAZ WindFree 12000 BTU Frio",
    codigoBusca: ["AR12MVPXAWKNAZ", "AR12MVPX", "AR12MVPXAWK", "SAMSUNG AR12MVPXAWKNAZ", "SAMSUNG WINDFREE 12000"],
    linha: "WindFree",
    tipo: "Split Hi Wall Inverter",
    capacidade: "12000 BTU/h",
    correnteNominal: "Validar etiqueta da unidade externa AR12MVPXAWKNAZ",
    correnteTrabalho: "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    disjuntor: "Validar manual do codigo exato e instalacao local",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    manualInstalacao: "https://www.samsung.com/br/support/model/AR12MVPXAWKNAZ/",
    manualManutencao: "https://www.samsung.com/br/support/model/AR12MVPXAWKNAZ/",
    fonte: "Base tecnica HVAC PRO - Samsung AR12MVPXAWKNAZ",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      correnteNominal: "INFORMACAO_SUGERIDA",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      disjuntor: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "Elgin",
    modelo: "Elgin Eco Inverter II Wi-Fi HJFC09C2WBCB 9000 BTU Frio 220V",
    codigoBusca: ["HJFC09C2WBCB", "HJFI09C2WB", "HJFE09C2CB", "ELGIN HJFC09", "ELGIN 9000 R32", "ELGIN 9000 FRIO"],
    linha: "Eco Inverter II Wi-Fi",
    tipo: "Split Hi Wall Inverter Frio",
    capacidade: "9000 BTU/h",
    tensao: "220V",
    fluidoRefrigerante: "R32",
    cargaGas: "Validar etiqueta da condensadora HJFE/HJFC 09",
    correnteNominal: "7,3 A corrente maxima",
    correnteTrabalho: "Inverter: medir em operacao estabilizada e comparar com etiqueta",
    disjuntor: "10 A",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    tubulacaoAlta: "1/4 pol.",
    tubulacaoBaixa: "3/8 pol.",
    comprimentoMaximo: "15 m",
    desnivelMaximo: "7 m",
    manualInstalacao: "https://www.elgin.com.br/manuals",
    manualManutencao: "https://www.elgin.com.br/manuals",
    fonte: "Base tecnica HVAC PRO - Elgin Eco Inverter II 9000",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      tensao: "CONFIAVEL_NAO_OFICIAL",
      fluidoRefrigerante: "CONFIAVEL_NAO_OFICIAL",
      cargaGas: "INFORMACAO_SUGERIDA",
      correnteNominal: "CONFIAVEL_NAO_OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      disjuntor: "CONFIAVEL_NAO_OFICIAL",
      capacitor: "INFORMACAO_SUGERIDA",
      tubulacaoAlta: "CONFIAVEL_NAO_OFICIAL",
      tubulacaoBaixa: "CONFIAVEL_NAO_OFICIAL",
      comprimentoMaximo: "CONFIAVEL_NAO_OFICIAL",
      desnivelMaximo: "CONFIAVEL_NAO_OFICIAL"
    }
  },

  {
    marca: "Elgin",
    modelo: "Elgin Eco Inverter II Wi-Fi HJFC12C2WBCB 12000 BTU Frio 220V",
    codigoBusca: ["HJFC12C2WBCB", "HJFI12C2WB", "HJFE12C2CB", "ELGIN HJFC12", "ELGIN 12000 R32", "ELGIN 12000 FRIO"],
    linha: "Eco Inverter II Wi-Fi",
    tipo: "Split Hi Wall Inverter Frio",
    capacidade: "12000 BTU/h",
    tensao: "220V",
    fluidoRefrigerante: "R32",
    cargaGas: "Validar etiqueta da condensadora HJFE/HJFC 12",
    correnteNominal: "6,7 A corrente maxima",
    correnteTrabalho: "Inverter: medir em operacao estabilizada e comparar com etiqueta",
    disjuntor: "10 A",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    tubulacaoAlta: "1/4 pol.",
    tubulacaoBaixa: "3/8 pol.",
    comprimentoMaximo: "15 m",
    desnivelMaximo: "7 m",
    manualInstalacao: "https://www.elgin.com.br/manuals",
    manualManutencao: "https://www.elgin.com.br/manuals",
    fonte: "Base tecnica HVAC PRO - Elgin Eco Inverter II 12000",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      tensao: "CONFIAVEL_NAO_OFICIAL",
      fluidoRefrigerante: "CONFIAVEL_NAO_OFICIAL",
      cargaGas: "INFORMACAO_SUGERIDA",
      correnteNominal: "CONFIAVEL_NAO_OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      disjuntor: "CONFIAVEL_NAO_OFICIAL",
      capacitor: "INFORMACAO_SUGERIDA",
      tubulacaoAlta: "CONFIAVEL_NAO_OFICIAL",
      tubulacaoBaixa: "CONFIAVEL_NAO_OFICIAL",
      comprimentoMaximo: "CONFIAVEL_NAO_OFICIAL",
      desnivelMaximo: "CONFIAVEL_NAO_OFICIAL"
    }
  },

  {
    marca: "Komeco",
    modelo: "Komeco KOHI09QC1HV Inverter 9000 BTU",
    codigoBusca: ["KOHI09QC1HV", "KOHI 09QC 1HV", "KOHI 09", "KOMECO KOHI 09QC", "KOMECO 9000"],
    linha: "KOHI Inverter",
    tipo: "Split Hi Wall Inverter",
    capacidade: "9000 BTU/h",
    fluidoRefrigerante: "A2L baixa inflamabilidade conforme manual da linha",
    cargaGas: "Validar etiqueta da unidade externa KOHI 09",
    correnteNominal: "Validar etiqueta do conjunto KOHI09QC1HV",
    correnteTrabalho: "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    disjuntor: "Validar tabela eletrica do manual e instalacao local",
    capacitor: "Inverter: validar manual tecnico/diagrama antes de substituir componente",
    manualInstalacao: "https://www.komeco.com.br/arquivos/manuais/ar-condicionado/split-hi-wall/manual-ar-condicionado-inverter-kohi.pdf",
    manualManutencao: "https://www.komeco.com.br/portaltecnico/LINHA%20DE%20CONDICIONADORES%20DE%20AR/Manuais%20Tecnicos/MANUAL%20DE%20SERVICO%20INVERTER.PDF",
    fonte: "Base tecnica HVAC PRO - Komeco KOHI 09",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      fluidoRefrigerante: "OFICIAL",
      cargaGas: "INFORMACAO_SUGERIDA",
      correnteNominal: "INFORMACAO_SUGERIDA",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      disjuntor: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "Komeco",
    modelo: "Komeco KOHI12QC1HV Inverter 12000 BTU",
    codigoBusca: ["KOHI12QC1HV", "KOHI 12QC 1HV", "KOHI 12", "KOMECO KOHI 12QC", "KOMECO 12000"],
    linha: "KOHI Inverter",
    tipo: "Split Hi Wall Inverter",
    capacidade: "12000 BTU/h",
    fluidoRefrigerante: "A2L baixa inflamabilidade conforme manual da linha",
    cargaGas: "Validar etiqueta da unidade externa KOHI 12",
    correnteNominal: "Validar etiqueta do conjunto KOHI12QC1HV",
    correnteTrabalho: "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    disjuntor: "Validar tabela eletrica do manual e instalacao local",
    capacitor: "Inverter: validar manual tecnico/diagrama antes de substituir componente",
    manualInstalacao: "https://www.komeco.com.br/arquivos/manuais/ar-condicionado/split-hi-wall/manual-ar-condicionado-inverter-kohi.pdf",
    manualManutencao: "https://www.komeco.com.br/portaltecnico/LINHA%20DE%20CONDICIONADORES%20DE%20AR/Manuais%20Tecnicos/MANUAL%20DE%20SERVICO%20INVERTER.PDF",
    fonte: "Base tecnica HVAC PRO - Komeco KOHI 12",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      fluidoRefrigerante: "OFICIAL",
      cargaGas: "INFORMACAO_SUGERIDA",
      correnteNominal: "INFORMACAO_SUGERIDA",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      disjuntor: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "Consul",
    modelo: "Consul CBK12EBBCJ Dual Inverter Cobre Frio 12000 BTU",
    codigoBusca: ["CBK12EBBCJ", "CBK12EB", "CONSUL CBK12EBBCJ", "CONSUL 12000", "CONSUL COBRE FRIO"],
    linha: "Dual Inverter Cobre Frio",
    tipo: "Split Hi Wall Inverter",
    capacidade: "12000 BTU/h",
    manualInstalacao: "https://www.consul.com.br/ar-condicionado-split-consul-dual-inverter-cobre-frio-12000-btus-cbk12eb/p",
    manualManutencao: "https://www.consul.com.br/atendimento/perguntas-frequentes/problemas-com-o-produto/manual-de-instrucoes-como-encontrar",
    fonte: "Base tecnica HVAC PRO - Consul CBK12EBBCJ",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL"
    }
  },

  {
    marca: "Consul",
    modelo: "Consul CBK12DBXCJ Triple Inverter Cobre Frio 12000 BTU",
    codigoBusca: ["CBK12DBXCJ", "CBK12DB", "CONSUL CBK12DBXCJ", "CONSUL TRIPLE INVERTER", "CONSUL 12000 TRIPLE"],
    linha: "Triple Inverter Cobre Frio",
    tipo: "Split Hi Wall Inverter",
    capacidade: "12000 BTU/h",
    correnteTrabalho: "Inverter: corrente varia conforme rotacao do compressor e carga termica",
    capacitor: "Inverter: validar placa/diagrama do modelo exato antes de substituir componente",
    manualInstalacao: "https://www.consul.com.br/ar-condicionado-split-consul-triple-inverter-cobre-frio-12000-btus-cbk12dbxcj/p",
    manualManutencao: "https://www.consul.com.br/atendimento/perguntas-frequentes/problemas-com-o-produto/manual-de-instrucoes-como-encontrar",
    fonte: "Base tecnica HVAC PRO - Consul CBK12DBXCJ",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "Hisense",
    modelo: "Hisense Hi-Smart Inverter 12000 BTU",
    codigoBusca: ["HISENSE 12000", "HISENSE HI SMART 12000", "HI-SMART 12000", "HISENSE INVERTER 12000"],
    linha: "Hi-Smart Inverter",
    tipo: "Split Hi Wall Inverter",
    capacidade: "12000 BTU/h",
    correnteTrabalho: "Inverter: corrente varia por carga termica e modo de operacao",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    manualInstalacao: "https://www.hisense.com.br/ar-condicionado/split-hi-smart/",
    manualManutencao: "https://www.hisense.com.br/ar-condicionado/split-hi-smart/",
    fonte: "Base tecnica HVAC PRO - Hisense Hi-Smart 12000",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA"
    }
  },

  {
    marca: "EOS",
    modelo: "EOS Master Inverter R32 12000 BTU",
    codigoBusca: ["EOS 12000", "EOS MASTER 12000", "EOS MASTER INVERTER 12000", "EOS R32 12000"],
    linha: "Master Inverter",
    tipo: "Split Hi Wall Inverter",
    capacidade: "12000 BTU/h",
    fluidoRefrigerante: "R32",
    correnteTrabalho: "Inverter: corrente varia por carga termica e modo de operacao",
    capacitor: "Inverter: validar placa/diagrama do modelo exato",
    manualInstalacao: "https://eos.com.br/ar-condicionado-eos-master-inverter/",
    manualManutencao: "https://eos.com.br/downloads/",
    fonte: "Base tecnica HVAC PRO - EOS Master 12000",
    fonteTipo: "FABRICANTE_OFICIAL",
    nivelConfianca: "OFICIAL",
    status: "OFICIAL",
    confiancaCampos: {
      marca: "OFICIAL",
      modelo: "OFICIAL",
      linha: "OFICIAL",
      tipo: "OFICIAL",
      capacidade: "OFICIAL",
      fluidoRefrigerante: "OFICIAL",
      correnteTrabalho: "INFORMACAO_SUGERIDA",
      capacitor: "INFORMACAO_SUGERIDA"
    }
  }
];
